src/CoreReact/Controllers/PlayerProfilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CoreReact.Data;
using CoreReact.Models;
using CoreReact.Models.ModelWrappers;
using CoreReact.Services;
using Microsoft.AspNetCore.Http;

namespace CoreReact.Controllers
{
    public class PlayerProfilesController : Controller
    {
        private readonly PlayerProfileDbContext _context;

        public PlayerProfilesController(PlayerProfileDbContext context)
        {
            _context = context;    
        }

        // GET: PlayerProfiles
        public async Task<IActionResult> Index()
        {
            return View(await _context.PlayerProfile.ToListAsync());
        }

        // GET: PlayerProfiles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var playerProfile = await _context.PlayerProfile.SingleOrDefaultAsync(m => m.Id == id);
            if (playerProfile == null)
            {
                return NotFound();
            }

            return View(playerProfile);
        }

        // GET: PlayerProfiles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PlayerProfiles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,PlayerId")] PlayerProfile playerProfile)
        {
            if (ModelState.IsValid)
            {   var existingPlayerProfile= await _context.PlayerProfile.SingleOrDefaultAsync(m => m.PlayerId==playerProfile.PlayerId);
                if (existingPlayerProfile == null)
                {
                    _context.Add(playerProfile);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                else
                {   //TODO: IMPLEMENT PLAYER ALREADY EXISTS VIEW
                    Console.WriteLine("ERROR! PLAYER ALREADY EXISTS WITH ID {0}",playerProfile.PlayerId);
                }
            }
            return View(playerProfile);
        }

        // GET: PlayerProfiles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var playerProfile = await _context.PlayerProfile.SingleOrDefaultAsync(m => m.Id == id);
            if (playerProfile == null)
            {
                return NotFound();
            }
            return View(playerProfile);
        }

        // POST: PlayerProfiles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,PlayerId,PpgInWin,PpgInLoss,ToPgInWin,ToPgInLoss,ApgInWin," +
                                                            "ApgInLoss,RpgInWin,RpgInLoss,FgPerInWin,FgPerInLoss,ThreePerInWin,ThreePerInLoss")] PlayerProfile playerProfile)
        { 
            if (id != playerProfile.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {    
                    _context.Update(playerProfile);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlayerProfileExists(playerProfile.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(playerProfile);
        }

        // GET: PlayerProfiles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var playerProfile = await _context.PlayerProfile.SingleOrDefaultAsync(m => m.Id == id);
            if (playerProfile == null)
            {
                return NotFound();
            }

            return View(playerProfile);
        }

        // POST: PlayerProfiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var playerProfile = await _context.PlayerProfile.SingleOrDefaultAsync(m => m.Id == id);
            _context.PlayerProfile.Remove(playerProfile);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool PlayerProfileExists(int id)
        {
            return _context.PlayerProfile.Any(e => e.Id == id);
        }
        //CANNOT SEND PRIMITIVES LIKE STRINGS ANYMORE CAN ONLY SEND WRAPPER MODEL OBJECTS
        [HttpPost]
        public async Task<String> UpdateAverages([FromBody ] LogJsonWrapper playerStatWrapper)
        {   //parse id, and player stat averages from the json String. Search for the play in the db. context and update based on averages.

            PlayerLogStatsService statCalculatorService=new PlayerLogStatsService();
            int id = statCalculatorService.GetPlayerStatId(playerStatWrapper);
            var playerProfile = await _context.PlayerProfile.SingleOrDefaultAsync(m => m.PlayerId == id);
            if (playerProfile == null)
            {
                return "Nope";
            }
            _context.PlayerProfile.Attach(playerProfile);
            playerProfile = statCalculatorService.CalculateAndUpdateStats(playerProfile,playerStatWrapper);
            await _context.SaveChangesAsync();
            return "Success";
        }
    }
}

src/CoreReact/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreReact</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
    </environment>
  <!---- Html.ApplicationInsightsJavaScript(TelemetryConfiguration)> --->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react-with-addons.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react-dom.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/remarkable/1.7.1/remarkable.min.js"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CoreReact</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="PlayerProfiles" asp-action="Index">Player Stats</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
<div class="container body-content">
    @RenderBody()
    <hr />
    <footer>
        <p>&copy; 2017 - CoreReact</p>
    </footer>
</div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script src="~/js/playerProfiles.min.js" asp-append-version="true"></script>
    @RenderSection("scripts", required: false)
</body>
</html>